Accessibility
Joaquin123455/microverse-portfolio pull request #7
Opened 2023-04-04 21:19 UTC by Joaquin123455

### General requirements

- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### HTML/CSS requirements

- Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### Project requirements

_**IMPORTANT NOTE:** For each Microverse project, you need to create a separate pull request. [Read how to work with multiple pull requests in your one repository in the most efficient way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md)._

- Check all of the items listed in the article [Easy Checks – A First Review of Web Accessibility](https://www.w3.org/WAI/test-evaluate/preliminary/) (which you already read in the previous lesson).
- Determine if your Portfolio needs any changes.
- Make changes in a separate branch and open a new pull request.
- Prepare a report listing all points that you have checked, and the result of your evaluation.
- Your report should include:
     -  List all points that you have checked, i.e:
        - [Page titles](https://www.w3.org/WAI/test-evaluate/preliminary/#title)
        - [Image text alternatives** (`<img alt="alt text">`)](https://www.w3.org/WAI/test-evaluate/preliminary/#images)
        - [Text headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings)
        - [Color contrast](https://www.w3.org/WAI/test-evaluate/preliminary/#contrast)
        - [Resize](https://www.w3.org/WAI/test-evaluate/preliminary/#resize)
        - [Interaction](https://www.w3.org/WAI/test-evaluate/preliminary/#interaction) 
          (labels are optional but recommended as voiceover tools can read them, and should be set as invisible to match the Figma design)
        - [Moving content](https://www.w3.org/WAI/test-evaluate/preliminary/#moving)
        - [Multimedia](https://www.w3.org/WAI/test-evaluate/preliminary/#media)
        - [The basic structure of the page](https://www.w3.org/WAI/test-evaluate/preliminary/#structure)
     - Each point on the list needs to include the result of your evaluation:
        - If everything was ok, make a statement about that (e.g. "Page titles - no issues found").
        - If you needed to change something, [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).
- Add your report to the description of your pull request.

2023-04-04 21:51 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

_**I decided to make my comments here because I could not make inline comments on your code. Kindly use the screenshots to trace where changes are required.**_

- [ ] It is part of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) to prepare a report listing all points that you have checked, and the result of your evaluation. This should be present in your PR description.
Below is the example of how to prepare your report.

```
- Page titles - no issues found. Provided not issues found, but if there's issue, you're ought to resolve that before making your report.
- Image text alternative - no issues found.
- etc. .......
```

- [ ] The title in the head section of your page is not descriptive. Something like `Joaquin's Portfolio` could be a nice option. Kindly fix that.

![your-title](https://user-images.githubusercontent.com/26597432/229928621-57fda05c-26b9-4089-acb7-084204d99ec2.png)

- [ ] This is the main title on your page, for convention, semantics reason, it should be wrapped in `h1` tag and it should only be one on a webpage. Kindly fix that.

![your-main-title](https://user-images.githubusercontent.com/26597432/229929265-6f5b7ea8-78a5-43f6-bbae-b6fac907f985.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 15:22 UTC, Joaquin123455 commented on desktop.css
> +    color: var(--my-contrast-color);
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on index.html
> +  <title>Joaquin's Portfolio</title>
structure changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on index.html
> +      <h1 class="main-title"> I'm Joaquin. <br>
structure changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #214073;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  font-weight: 700;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #214073;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  border: 1px solid #1f35ff;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: black;
contrast color changed.

2023-04-05 15:22 UTC, Joaquin123455 commented on style.css
> +  color: #1f35ff;
contrast color changed.

2023-04-05 15:27 UTC, AdnanOlarmmi approved these changes
Hi @Joaquin123455,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- App is now accessible.
- 😊 Yay! You fixed the changes

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 15:28 UTC, merged